// Browser integration checks. Node.js + Playwright are development-only dependencies.
// Optional: LORA_VIEWER_BROWSER, LORA_VIEWER_PLAYWRIGHT_MODULE, LORA_VIEWER_ARTIFACTS.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const {chromium}=require(process.env.LORA_VIEWER_PLAYWRIGHT_MODULE||'playwright');
const output=process.env.LORA_VIEWER_ARTIFACTS||fs.mkdtempSync(path.join(os.tmpdir(),'lora-viewer-test-'));
fs.mkdirSync(output,{recursive:true});
const viewer=path.resolve(__dirname,'../tools/lora_comparison.html');
const chart=(id,series,x=[0,1,2,3],x_label='TrainStep')=>({id,title:id,x_label,x,series});
const report=(name,offset=0)=>({base_name:name,generated_at:'2026-09-06 12:00:00',charts:{grad:[chart('loss_ma',[{name:'Loss',y:[3+offset,null,1+offset,offset]},{name:'Loss MA',y:[3+offset,null,1+offset,offset]}]),chart('cosine',[{name:'CosineSim',y:[null,null,null,null]}]),chart('thresh_off',[{name:'ThreshOff',y:[0,0,0,0]}])],rank:[chart('rank_dim',[{name:'RankDim',y:[4,4,4,4]}])],group_loss:[chart('group_loss_ema_epoch',[{name:'subject',y:[3,2,1]}],[1,2,3],'Epoch')]},rank:{final_heatmaps:{rank_sat_wmean:{Epoch:3,TrainStep:3,Scope:'unet',rows:[{label:'down',cells:[{role:'to_q',value:0},{role:'to_k',value:null}]},{label:'up',cells:[{role:'to_q',value:0.8+offset*.01},{role:'to_k',value:0.5}]}]}}}});
const payload=(name,data)=>({name,mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.LORA_VIEWER_BROWSER?{executablePath:process.env.LORA_VIEWER_BROWSER}:{})});
 const page=await browser.newPage({viewport:{width:1440,height:1100},acceptDownloads:true});
 const errors=[],network=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route(/^https?:/,route=>{network.push(route.request().url());route.abort()});
 await page.goto(pathToFileURL(viewer).href);
 assert(await page.locator('#dropzone').isVisible());
 const a=report('baseline'),b=report('candidate',1);
 a.training_settings={schema_version:1,source:'record',status:'recorded',values:{seed:0,avg_cp:false,unet_lr:null,learning_rate:0.001,network_args:{a:1,b:2}},resolved:{runtime:{dq_auto_preset:'clip_rate_high'},optimizer_groups_created:[{label:'TE1',options:{lr:0.0003}}]}};
 b.training_settings={schema_version:1,source:'metadata',status:'partial',values:{seed:0,unet_lr:null,learning_rate:0.002,network_args:{b:2,a:1}}};
 await page.locator('#file-input').setInputFiles([payload('a.json',a),payload('b.json',b)]);
 await page.waitForFunction(()=>document.querySelectorAll('.run-card').length===2);
 await page.locator('#training-settings > summary').click();
 assert.equal(await page.locator('#settings-table tr').filter({hasText:'設定 / seed'}).count(),0,'equal setting hidden');
 assert.equal(await page.locator('#settings-table tr').filter({hasText:'設定 / network_args'}).count(),0,'object key order ignored');
 assert.deepEqual(await page.locator('#settings-table tr').filter({hasText:'設定 / avg_cp'}).locator('td').allTextContents(),['設定 / avg_cp','false','未記録']);
 assert((await page.locator('#settings-table').innerText()).includes('0.0003'),'actual optimizer LR shown separately');
 await page.locator('#settings-differences').uncheck();
 assert.deepEqual(await page.locator('#settings-table tr').filter({hasText:'設定 / seed'}).locator('td').allTextContents(),['設定 / seed','0','0']);
 assert((await page.locator('#settings-table tr').filter({hasText:'設定 / unet_lr'}).innerText()).includes('None（指定なし）'));
 await page.locator('#settings-differences').check();
 await page.locator('#training-settings > summary').click();
 assert.equal(await page.locator('#plots path[data-series]').count(),2);
 assert.equal(await page.locator('[data-chart-id="cosine"]').count(),0,'empty cosine omitted');
 assert(await page.locator('[data-chart-id="thresh_off"]').count(),'zero retained');
 assert(await page.locator('[data-chart-id="group_loss_epoch_ema"]').count(),'legacy alias normalized');
 const curve=await page.locator('#plots path[data-series]').first().getAttribute('d');
 assert.equal((curve.match(/M/g)||[]).length,2,'gap must break path');
 await page.selectOption('#mode','difference');
 assert.equal(await page.locator('#plots path[data-series]').count(),1);
 assert.deepEqual(await page.locator('#stats-body tr').first().locator('td').allTextContents(),['candidate','Loss MA','3','1','1','1','1'],'difference excludes null and keeps exact values');
 await page.selectOption('#mode','panels');
 assert.equal(await page.locator('#plots svg').count(),2);
 const yTicks=await page.locator('#plots svg').evaluateAll(es=>es.map(e=>[...e.querySelectorAll('text[text-anchor="end"]')].map(t=>t.textContent)));
 assert.deepEqual(yTicks[0],yTicks[1],'facets use common scale');
 await page.selectOption('#range','custom');await page.fill('#range-min','2');await page.fill('#range-max','3');await page.click('#apply-range');
 assert.deepEqual((await page.locator('#stats-body tr').first().locator('td').allTextContents()).slice(0,4),['baseline','Loss MA','2','0.5']);
 await page.selectOption('#range','all');await page.selectOption('#mode','overlay');
 await page.locator('#plots [data-hover-overlay]').hover({position:{x:50,y:40}});
 assert(await page.locator('#tooltip').isVisible());
 await page.locator('#plots [data-hover-overlay]').click({position:{x:50,y:40}});await page.locator('h1').hover();
 assert(await page.locator('#tooltip').isVisible(),'click pins hover');await page.keyboard.press('Escape');
 assert(!await page.locator('#tooltip').isVisible());
 await page.click('[data-chart-id="heat_rank_sat_wmean"]');
 assert.equal(await page.locator('.heat-table').count(),2);
 assert((await page.locator('.heat-table').first().innerText()).includes('0.0000'),'zero heat cell retained');
 assert((await page.locator('.heat-table').first().innerText()).includes('—'),'missing heat cell stays missing');
 await page.click('[data-chart-id="loss_ma"]');
 await page.locator('#file-input').setInputFiles(payload('same-content.json',a));
 await page.waitForFunction(()=>document.getElementById('errors').textContent.includes('同じ内容'));
 assert.equal(await page.locator('.run-card').count(),2);
 const evil=report('</script><img src=x onerror="window.XSS=1">',2);
 evil.training_settings={schema_version:1,source:'metadata',status:'partial',values:{danger:'</script><img src=x onerror="window.XSS=1">'},resolved:{optimizer_groups_created:[null,{options:null}]}};
 await page.locator('#file-input').setInputFiles([payload('evil.json',evil),{name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{broken')},payload('wrong.json',{other:1})]);
 await page.waitForFunction(()=>document.querySelectorAll('.run-card').length===3&&!document.getElementById('add-files').disabled);
 assert.equal(await page.locator('img').count(),0);assert.equal(await page.evaluate(()=>window.XSS),undefined);
 assert((await page.locator('#errors').innerText()).includes('wrong.json'));
 await page.selectOption('#mode','panels');
 const downloadEvent=page.waitForEvent('download');await page.click('#save');const download=await downloadEvent;
 const saved=path.join(output,'saved-comparison.html');await download.saveAs(saved);
 const stored=fs.readFileSync(saved,'utf8');assert(stored.includes('\\u003c/script>'),'script content escaped');
 await page.goto(pathToFileURL(saved).href);
 assert.equal(await page.locator('.run-card').count(),3);assert.equal(await page.locator('#mode').inputValue(),'panels');assert.equal(await page.locator('#plots svg').count(),3);assert.equal(await page.locator('img').count(),0);
 assert((await page.locator('#settings-table').textContent()).includes('0.0003'),'settings survive saved comparison');
 await page.locator('#file-input').setInputFiles([payload('d.json',report('fourth',3)),payload('e.json',report('fifth',4))]);
 await page.waitForFunction(()=>document.querySelectorAll('.run-card').length===5);
 assert.equal(await page.locator('.run-top input:checked').count(),4);
 const results=[];
 for(const width of [1440,736,390])for(const colorScheme of ['light','dark']){
  await page.setViewportSize({width,height:1000});await page.emulateMedia({colorScheme});await page.waitForTimeout(200);
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  assert(!overflow,`page overflow ${width}/${colorScheme}`);
  const marks=await page.locator('#plots path[data-series]').evaluateAll(es=>es.map(e=>e.getTotalLength()));assert(marks.every(n=>n>0));
  results.push({width,colorScheme,marks:marks.length,overflow});
 }
 // Fixed bounds must affect actual rendered geometry, while differences remain automatic.
 const fixedReport=(name,bounds,offset=0)=>({base_name:name,charts:{grad:[{...chart('bounded',[{name:'value',y:[.80+offset,.81+offset]}],[0,1]),...bounds}]}});
 const readAxes=()=>page.locator('#plots svg').evaluateAll(es=>es.map(e=>[...e.querySelectorAll('text[text-anchor="end"]')].map(t=>t.textContent)));
 const loadBounds=async(left,right)=>{
  await page.goto(pathToFileURL(viewer).href);
  await page.locator('#file-input').setInputFiles([payload('bounds-a.json',fixedReport('bounds-a',left)),payload('bounds-b.json',fixedReport('bounds-b',right,.01))]);
 };
 await loadBounds({y_min_fixed:0,y_max_fixed:1},{y_min_fixed:0,y_max_fixed:1});
 const boundedAxes=await readAxes();assert.equal(Number(boundedAxes[0][0]),0);assert.equal(Number(boundedAxes[0].at(-1)),1);
 const relativeHeight=await page.locator('#plots svg').first().evaluate(e=>e.querySelector('path[data-series]').getBBox().height/e.querySelector('[data-chart-frame]').height.baseVal.value);
 assert(Math.abs(relativeHeight-.01)<1e-6,'0.01 change occupies 1% of fixed 0..1 plot');
 await page.selectOption('#mode','panels');assert.deepEqual(await readAxes(),[boundedAxes[0],boundedAxes[0]],'fixed panels share overlay scale');
 await page.selectOption('#mode','difference');const differenceAxes=await readAxes();
 await loadBounds({},{});await page.selectOption('#mode','difference');assert.deepEqual(await readAxes(),differenceAxes,'difference scale ignores original fixed bounds');
 await loadBounds({y_min_fixed:0},{y_min_fixed:0});
 const lowerAxes=(await readAxes())[0].map(Number);assert.equal(lowerAxes[0],0);assert(lowerAxes.at(-1)<1,'upper end remains automatic');
 await loadBounds({y_max_fixed:1},{y_max_fixed:1});
 const upperAxes=(await readAxes())[0].map(Number);assert(upperAxes[0]>.7,'lower end remains automatic');assert.equal(upperAxes.at(-1),1);
 await loadBounds({y_min_fixed:0,y_max_fixed:1},{y_min_fixed:-1,y_max_fixed:2});
 const unionAxes=(await readAxes())[0].map(Number);assert.equal(unionAxes[0],-1);assert.equal(unionAxes.at(-1),2,'different fixed bounds use their union');
 await loadBounds({y_min_fixed:0,y_max_fixed:.5},{});
 const mixedAxes=(await readAxes())[0].map(Number);assert.equal(mixedAxes[0],0);assert(mixedAxes.at(-1)>=.8,'older report without fixed bounds keeps its data in view');
 const boundsDownloadEvent=page.waitForEvent('download');await page.click('#save');const boundsDownload=await boundsDownloadEvent;
 const savedBounds=path.join(output,'fixed-bounds.html');await boundsDownload.saveAs(savedBounds);await page.goto(pathToFileURL(savedBounds).href);
 assert.deepEqual((await readAxes())[0].map(Number),mixedAxes,'bounds survive save/reopen');
 // Non-fixed bounds and tick metadata are preserved through imports and save/reopen.
 const axisReport=(name,id,bounds,ys,reference=null)=>({base_name:name,charts:{dq:[{...chart(id,[{name:'value',y:ys},...(reference===null?[]:[{name:'reference',y:ys.map(()=>reference)}])],ys.map((_,i)=>i)),...bounds}]}});
 const loadAxes=async(id,left,right,ys=[8,8],reference=null)=>{
  await page.goto(pathToFileURL(viewer).href);
  await page.locator('#file-input').setInputFiles([payload('axis-a.json',axisReport('axis-a',id,left,ys,reference)),payload('axis-b.json',axisReport('axis-b',id,right,ys,reference))]);
 };
 const bitsBounds={y_min_floor:0,y_tick_step:1,y_tick_integer:true};
 await loadAxes('dq_bits',bitsBounds,bitsBounds);
 const bitsAxes=(await readAxes())[0];assert.equal(bitsAxes[0],'0');assert(bitsAxes.includes('8'));assert(bitsAxes.every(t=>/^\d+$/.test(t)),'bits have integer labels');
 await page.selectOption('#mode','panels');assert.deepEqual(await readAxes(),[bitsAxes,bitsAxes],'panels share constrained ticks');
 await page.selectOption('#mode','difference');const bitsDifferenceAxes=await readAxes();
 await loadAxes('dq_bits',{},{});await page.selectOption('#mode','difference');assert.deepEqual(await readAxes(),bitsDifferenceAxes,'difference ignores all source axis metadata');
 await loadAxes('dq_bits',bitsBounds,bitsBounds,[-2,8]);assert(Number((await readAxes())[0][0])<=-2,'floor expands range instead of clipping negative observations');
 const qerrBounds={y_min_fixed:0,y_max_ceil:100,y_tick_step:25,y_tick_precision:0};
 await loadAxes('dq_qerr_per_clip',qerrBounds,qerrBounds,[20,30],100);
 await page.locator('#series-box').evaluate(e=>e.open=true);await page.locator('#series-list input[value="reference"]').uncheck();
 assert.deepEqual((await readAxes())[0],['0','25','50','75','100'],'reference ceiling remains after hiding its series');
 assert.equal(await page.locator('#plots path[data-series="reference"]').count(),0);
 const axisDownloadEvent=page.waitForEvent('download');await page.click('#save');const axisDownload=await axisDownloadEvent;
 const savedAxis=path.join(output,'axis-constraints.html');await axisDownload.saveAs(savedAxis);await page.goto(pathToFileURL(savedAxis).href);
 assert.deepEqual((await readAxes())[0],['0','25','50','75','100'],'non-fixed bounds and ticks survive saved HTML');
 await loadAxes('dq_qerr_per_clip',qerrBounds,qerrBounds,[120,150]);assert(Number((await readAxes())[0].at(-1))>=150,'ceiling never clips observations above reference');
 const decimalBounds={y_min_fixed:0,y_max_fixed:1,y_tick_step:.1,y_tick_precision:1};
 await loadAxes('decimal',decimalBounds,decimalBounds,[.8,.81]);
 assert.equal((await readAxes())[0][0],'0.0');assert.equal((await readAxes())[0].at(-1),'1.0');assert((await readAxes())[0].includes('0.1'),'decimal interval and precision preserved');
 await loadAxes('integer',{y_tick_nice_integer:true},{y_tick_nice_integer:true},[7.9,8.1]);assert((await readAxes())[0].every(t=>/^\d+$/.test(t)),'nice integer ticks remain distinct');
 await loadAxes('mixed',decimalBounds,{...decimalBounds,y_tick_step:.25},[.8,.81]);
 const conflictAxes=(await readAxes())[0];assert.equal(new Set(conflictAxes).size,conflictAxes.length,'conflicting steps yield distinct common automatic ticks');
 await page.selectOption('#mode','panels');assert.deepEqual(await readAxes(),[conflictAxes,conflictAxes]);
 await loadAxes('tiny',{...decimalBounds,y_tick_step:1e-300},{...decimalBounds,y_tick_step:1e-300});assert((await readAxes())[0].length<=13,'tiny imported intervals cannot create unbounded ticks');
 // Only the baseline has a gap; target observations and statistics must stay unchanged.
 for(const id of ['loss_ma','dq_bits']){
  await page.goto(pathToFileURL(viewer).href);
  const base={base_name:'gap-base',charts:{grad:[chart(id,[{name:'value',y:[0,null,0]}],[0,1,2])]}},
        target={base_name:'gap-target',charts:{grad:[chart(id,[{name:'value',y:[1,1]}],[0,2])]}};
  await page.locator('#file-input').setInputFiles([payload('gap-base.json',base),payload('gap-target.json',target)]);
  await page.selectOption('#mode','difference');
  for(const axis of ['native','progress']){
   await page.selectOption('#axis',axis);
   const d=await page.locator('#plots path[data-series]').first().getAttribute('d');
   assert.equal((d.match(/M/g)||[]).length,2,`${id}/${axis}: split baseline-only gap`);
   assert.equal(await page.locator('#plots [data-point]').count(),2,'both isolated observations visible');
   assert.deepEqual((await page.locator('#stats-body tr').first().locator('td').allTextContents()).slice(2),['2','1','1','1','1'],'no synthetic observation in statistics');
  }
  await page.selectOption('#axis','native');
  await page.selectOption('#range','custom');await page.fill('#range-min','0');await page.fill('#range-max','1');await page.click('#apply-range');
  assert.equal((await page.locator('#stats-body tr').first().locator('td').allTextContents())[2],'1');
  await page.selectOption('#range','all');
  const event=page.waitForEvent('download');await page.click('#save');const download=await event;
  const savedGap=path.join(output,`gap-${id}.html`);await download.saveAs(savedGap);await page.goto(pathToFileURL(savedGap).href);
  assert.equal(((await page.locator('#plots path[data-series]').first().getAttribute('d')).match(/M/g)||[]).length,2,'gap survives save/reopen');
 }
 // Dense data must retain the boundary even when the SVG path is thinned.
 await page.goto(pathToFileURL(viewer).href);
 const xs=Array.from({length:10000},(_,i)=>i),ys=xs.map(()=>0);ys[5001]=null;
 const targetXs=xs.filter(x=>x!==5001),dense=(name,x,y)=>({base_name:name,charts:{grad:[chart('loss_ma',[{name:'value',y}],x)]}});
 await page.locator('#file-input').setInputFiles([payload('dense-base.json',dense('dense-base',xs,ys)),payload('dense-target.json',dense('dense-target',targetXs,targetXs.map(()=>1)))]);
 await page.selectOption('#mode','difference');
 assert.equal(((await page.locator('#plots path[data-series]').first().getAttribute('d')).match(/M/g)||[]).length,2,'thinning retains baseline gap boundary');
 assert.equal((await page.locator('#stats-body tr').first().locator('td').allTextContents())[2],'9,999');
 await browser.close();assert.deepEqual(network,[],'offline viewer must not request network');assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(output,'integration-results.json'),JSON.stringify({results,errors,network},null,2));
 console.log('PASS: imports, legacy IDs, gaps, zeros, differences, baseline-only gaps (native/progress/discrete/thinned/saved), shared scales, fixed/floor/ceiling bounds and tick metadata, ranges, hover, heatmaps, duplicate handling, malformed input, HTML safety, save/reopen, selection limit, responsive themes, offline.');
 console.log('Artifacts:',output);
})().catch(e=>{console.error(e);process.exit(1)});
